In [81]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [82]:
data = pd.read_csv("../data/allcountriesglobaltemperaturechange.csv")

In [83]:
data

,ObjectId,Country Name,Unit,Change,1970,1971,1972,1973,1974,1975,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1,"Afghanistan, Islamic Rep. of",Degree Celsius,Surface Temperature Change,0.898,0.652,-1.089,0.262,-0.470,-0.468,...,0.234,1.308,0.457,1.101,1.607,1.568,1.580,0.960,0.544,1.421
1,2,Albania,Degree Celsius,Surface Temperature Change,-0.119,-0.200,-0.077,-0.299,-0.134,-0.203,...,1.568,1.444,1.322,1.665,1.601,1.269,2.146,1.823,1.623,1.682
2,3,Algeria,Degree Celsius,Surface Temperature Change,0.114,-0.380,-0.342,-0.028,-0.502,-0.554,...,1.128,1.173,1.676,1.101,1.736,1.498,1.211,1.094,1.913,2.317
3,4,American Samoa,Degree Celsius,Surface Temperature Change,-0.036,-0.473,-0.070,0.322,-0.317,-0.128,...,0.646,0.883,0.554,0.394,0.924,0.820,0.574,0.924,0.815,0.653
4,5,"Andorra, Principality of",Degree Celsius,Surface Temperature Change,0.081,-0.355,-0.526,-0.010,-0.412,0.207,...,1.196,0.757,1.857,1.546,1.830,1.771,1.761,1.813,2.401,1.367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,223,Western Sahara,Degree Celsius,Surface Temperature Change,0.547,-0.620,-1.104,-0.013,-0.600,-0.267,...,1.234,1.282,1.244,1.277,1.636,2.078,0.851,1.430,2.026,1.557
223,224,World,Degree Celsius,Surface Temperature Change,0.153,-0.089,-0.193,0.271,-0.179,0.091,...,1.058,1.007,1.042,1.406,1.658,1.424,1.284,1.449,1.713,1.442
224,225,"Yemen, Rep. of",Degree Celsius,Surface Temperature Change,0.388,-0.199,0.049,0.333,-0.108,0.031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,226,Zambia,Degree Celsius,Surface Temperature Change,0.354,-0.249,-0.146,0.386,-0.393,-0.116,...,0.926,0.746,0.638,1.486,1.474,0.721,0.727,1.295,1.252,1.002
226,230,Zimbabwe,Degree Celsius,Surface Temperature Change,0.427,-0.033,-0.367,0.627,-0.471,-0.253,...,0.329,0.102,-0.008,0.808,1.051,0.116,0.405,0.939,0.415,-0.101

In [84]:
data.head(10)

,ObjectId,Country Name,Unit,Change,1970,1971,1972,1973,1974,1975,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1,"Afghanistan, Islamic Rep. of",Degree Celsius,Surface Temperature Change,0.898,0.652,-1.089,0.262,-0.470,-0.468,...,0.234,1.308,0.457,1.101,1.607,1.568,1.580,0.960,0.544,1.421
1,2,Albania,Degree Celsius,Surface Temperature Change,-0.119,-0.200,-0.077,-0.299,-0.134,-0.203,...,1.568,1.444,1.322,1.665,1.601,1.269,2.146,1.823,1.623,1.682
2,3,Algeria,Degree Celsius,Surface Temperature Change,0.114,-0.380,-0.342,-0.028,-0.502,-0.554,...,1.128,1.173,1.676,1.101,1.736,1.498,1.211,1.094,1.913,2.317
3,4,American Samoa,Degree Celsius,Surface Temperature Change,-0.036,-0.473,-0.070,0.322,-0.317,-0.128,...,0.646,0.883,0.554,0.394,0.924,0.820,0.574,0.924,0.815,0.653
4,5,"Andorra, Principality of",Degree Celsius,Surface Temperature Change,0.081,-0.355,-0.526,-0.010,-0.412,0.207,...,1.196,0.757,1.857,1.546,1.830,1.771,1.761,1.813,2.401,1.367
5,6,Angola,Degree Celsius,Surface Temperature Change,0.249,-0.092,-0.029,0.477,-0.152,-0.018,...,0.576,1.090,0.879,1.430,1.847,1.064,1.504,1.975,1.387,1.631
6,7,Anguilla,Degree Celsius,Surface Temperature Change,0.084,-0.222,-0.137,0.194,-0.327,-0.310,...,0.652,0.778,0.821,1.070,1.164,0.980,0.728,0.861,1.246,0.910
7,8,Antigua and Barbuda,Degree Celsius,Surface Temperature Change,0.080,-0.211,-0.174,0.203,-0.335,-0.382,...,0.682,0.766,0.723,1.032,1.105,0.965,0.694,0.806,1.141,0.873
8,9,Argentina,Degree Celsius,Surface Temperature Change,0.442,-0.263,-0.007,-0.155,-0.120,-0.031,...,0.787,0.437,0.951,0.953,0.492,1.100,0.876,0.756,1.109,1.011
9,10,"Armenia, Rep. of",Degree Celsius,Surface Temperature Change,NaN,NaN,NaN,NaN,NaN,NaN,...,1.272,1.407,1.258,1.921,1.339,0.901,2.781,1.853,1.966,2.212

In [85]:
data.tail(10)

,ObjectId,Country Name,Unit,Change,1970,1971,1972,1973,1974,1975,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
217,218,Vanuatu,Degree Celsius,Surface Temperature Change,0.308,-0.005,-0.314,0.550,0.312,0.043,...,0.342,0.649,0.554,0.536,1.102,1.032,0.445,0.803,1.146,1.067
218,219,"Venezuela, Rep. Bolivariana de",Degree Celsius,Surface Temperature Change,0.205,-0.366,-0.026,0.359,-0.316,-0.274,...,0.436,0.857,0.806,1.174,1.141,0.752,0.808,1.171,1.293,0.723
219,220,Vietnam,Degree Celsius,Surface Temperature Change,-0.036,-0.374,0.067,0.505,-0.328,0.213,...,0.818,0.992,0.638,1.327,1.283,1.213,0.905,1.864,1.588,1.193
220,221,Wallis and Futuna Islands,Degree Celsius,Surface Temperature Change,0.053,-0.042,-0.117,0.363,0.127,-0.022,...,0.617,0.683,0.606,0.646,1.159,0.960,0.688,1.110,1.082,0.775
221,222,West Bank and Gaza,Degree Celsius,Surface Temperature Change,0.216,-0.347,-0.488,-0.479,-0.268,-0.421,...,1.110,1.194,0.940,1.408,1.705,0.821,2.093,1.298,1.553,1.887
222,223,Western Sahara,Degree Celsius,Surface Temperature Change,0.547,-0.620,-1.104,-0.013,-0.600,-0.267,...,1.234,1.282,1.244,1.277,1.636,2.078,0.851,1.430,2.026,1.557
223,224,World,Degree Celsius,Surface Temperature Change,0.153,-0.089,-0.193,0.271,-0.179,0.091,...,1.058,1.007,1.042,1.406,1.658,1.424,1.284,1.449,1.713,1.442
224,225,"Yemen, Rep. of",Degree Celsius,Surface Temperature Change,0.388,-0.199,0.049,0.333,-0.108,0.031,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,226,Zambia,Degree Celsius,Surface Temperature Change,0.354,-0.249,-0.146,0.386,-0.393,-0.116,...,0.926,0.746,0.638,1.486,1.474,0.721,0.727,1.295,1.252,1.002
226,230,Zimbabwe,Degree Celsius,Surface Temperature Change,0.427,-0.033,-0.367,0.627,-0.471,-0.253,...,0.329,0.102,-0.008,0.808,1.051,0.116,0.405,0.939,0.415,-0.101

In [86]:
data.describe()

,ObjectId,1970,1971,1972,1973,1974,1975,1976,1977,1978,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,227.000000,190.000000,193.000000,195.000000,195.000000,193.000000,190.000000,192.000000,191.000000,192.000000,...,214.000000,216.000000,216.000000,216.000000,215.000000,214.000000,216.000000,215.000000,214.000000,214.000000
mean,114.013216,0.097689,-0.190124,-0.075354,0.230226,-0.168347,-0.024305,-0.243792,0.170592,0.079359,...,0.887421,0.917185,1.096120,1.252981,1.427991,1.269939,1.288102,1.427628,1.538565,1.317009
std,65.696573,0.354175,0.232647,0.385045,0.332191,0.291944,0.418103,0.321562,0.249489,0.291574,...,0.438641,0.329476,0.564232,0.461446,0.406105,0.393581,0.612291,0.475653,0.627076,0.518561
min,1.000000,-1.284000,-0.879000,-1.796000,-0.992000,-0.953000,-1.099000,-1.169000,-0.703000,-0.864000,...,0.007000,0.102000,-0.008000,0.170000,0.096000,0.116000,0.285000,0.062000,0.080000,-0.288000
25%,57.500000,-0.038750,-0.307000,-0.194500,0.047000,-0.335000,-0.271250,-0.430250,0.004000,-0.012750,...,0.574500,0.686750,0.722250,0.975250,1.141000,0.981250,0.815000,1.106000,1.140250,0.993250
50%,114.000000,0.133000,-0.206000,-0.026000,0.245000,-0.213000,-0.128000,-0.258000,0.183000,0.116000,...,0.788500,0.906000,0.943000,1.230500,1.434000,1.261000,1.130000,1.396000,1.468000,1.287500
75%,170.500000,0.293750,-0.069000,0.113500,0.452500,-0.060000,0.094000,-0.072500,0.325500,0.227250,...,1.144500,1.174750,1.354750,1.501750,1.725000,1.541250,1.762000,1.696500,1.891500,1.695500
max,230.000000,0.978000,0.683000,0.942000,1.147000,1.125000,1.898000,0.727000,1.084000,0.916000,...,2.165000,1.684000,2.711000,2.605000,2.454000,2.486000,2.781000,2.713000,3.693000,2.543000

In [87]:
data.dtypes

ObjectId          int64
Country Name        str
Unit                str
Change              str
1970            float64
1971            float64
1972            float64
1973            float64
1974            float64
1975            float64
1976            float64
1977            float64
1978            float64
1979            float64
1980            float64
1981            float64
1982            float64
1983            float64
1984            float64
1985            float64
1986            float64
1987            float64
1988            float64
1989            float64
1990            float64
1991            float64
1992            float64
1993            float64
1994            float64
1995            float64
1996            float64
1997            float64
1998            float64
1999            float64
2000            float64
2001            float64
2002            float64
2003            float64
2004            float64
2005            float64
2006            float64
2007            float64
2008            float64
2009            float64
2010            float64
2011            float64
2012            float64
2013            float64
2014            float64
2015            float64
2016            float64
2017            float64
2018            float64
2019            float64
2020            float64
2021            float64
dtype: object

In [88]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 227 entries, 0 to 226
Data columns (total 56 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ObjectId      227 non-null    int64
 1   Country Name  227 non-null    str
 2   Unit          227 non-null    str
 3   Change        227 non-null    str
 4   1970          190 non-null    float64
 5   1971          193 non-null    float64
 6   1972          195 non-null    float64
 7   1973          195 non-null    float64
 8   1974          193 non-null    float64
 9   1975          190 non-null    float64
 10  1976          192 non-null    float64
 11  1977          191 non-null    float64
 12  1978          192 non-null    float64
 13  1979          191 non-null    float64
 14  1980          193 non-null    float64
 15  1981          192 non-null    float64
 16  1982          192 non-null    float64
 17  1983          189 non-null    float64
 18  1984          190 non-null    float64
 19  1985          190 non-null    float64
 20  1986          191 non-null    float64
 21  1987          191 non-null    float64
 22  1988          191 non-null    float64
 23  1989          192 non-null    float64
 24  1990          191 non-null    float64
 25  1991          190 non-null    float64
 26  1992          211 non-null    float64
 27  1993          209 non-null    float64
 28  1994          209 non-null    float64
 29  1995          211 non-null    float64
 30  1996          211 non-null    float64
 31  1997          208 non-null    float64
 32  1998          212 non-null    float64
 33  1999          210 non-null    float64
 34  2000          211 non-null    float64
 35  2001          209 non-null    float64
 36  2002          212 non-null    float64
 37  2003          215 non-null    float64
 38  2004          214 non-null    float64
 39  2005          213 non-null    float64
 40  2006          216 non-null    float64
 41  2007          217 non-null    float64
 42  2008          213 non-null    float64
 43  2009          214 non-null    float64
 44  2010          215 non-null    float64
 45  2011          217 non-null    float64
 46  2012          214 non-null    float64
 47  2013          216 non-null    float64
 48  2014          216 non-null    float64
 49  2015          216 non-null    float64
 50  2016          215 non-null    float64
 51  2017          214 non-null    float64
 52  2018          216 non-null    float64
 53  2019          215 non-null    float64
 54  2020          214 non-null    float64
 55  2021          214 non-null    float64
dtypes: float64(52), int64(1), str(3)
memory usage: 99.4 KB

In [89]:
data.isnull().sum()

ObjectId         0
Country Name     0
Unit             0
Change           0
1970            37
1971            34
1972            32
1973            32
1974            34
1975            37
1976            35
1977            36
1978            35
1979            36
1980            34
1981            35
1982            35
1983            38
1984            37
1985            37
1986            36
1987            36
1988            36
1989            35
1990            36
1991            37
1992            16
1993            18
1994            18
1995            16
1996            16
1997            19
1998            15
1999            17
2000            16
2001            18
2002            15
2003            12
2004            13
2005            14
2006            11
2007            10
2008            14
2009            13
2010            12
2011            10
2012            13
2013            11
2014            11
2015            11
2016            12
2017            13
2018            11
2019            12
2020            13
2021            13
dtype: int64

In [90]:
data.duplicated().sum()

np.int64(0)

In [91]:
data.columns.tolist()

['ObjectId',
 'Country Name',
 'Unit',
 'Change ',
 '1970',
 '1971',
 '1972',
 '1973',
 '1974',
 '1975',
 '1976',
 '1977',
 '1978',
 '1979',
 '1980',
 '1981',
 '1982',
 '1983',
 '1984',
 '1985',
 '1986',
 '1987',
 '1988',
 '1989',
 '1990',
 '1991',
 '1992',
 '1993',
 '1994',
 '1995',
 '1996',
 '1997',
 '1998',
 '1999',
 '2000',
 '2001',
 '2002',
 '2003',
 '2004',
 '2005',
 '2006',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2021']

In [92]:
data["Country Name"].unique()

<StringArray>
[  'Afghanistan, Islamic Rep. of',                        'Albania',
                        'Algeria',                 'American Samoa',
       'Andorra, Principality of',                         'Angola',
                       'Anguilla',            'Antigua and Barbuda',
                      'Argentina',               'Armenia, Rep. of',
 ...
                        'Vanuatu', 'Venezuela, Rep. Bolivariana de',
                        'Vietnam',      'Wallis and Futuna Islands',
             'West Bank and Gaza',                 'Western Sahara',
                          'World',                 'Yemen, Rep. of',
                         'Zambia',                       'Zimbabwe']
Length: 227, dtype: str

In [93]:
data["Unit"].unique()

<StringArray>
['Degree Celsius']
Length: 1, dtype: str

In [94]:
data = data.drop(columns=["ObjectId"])

In [95]:
data

,Country Name,Unit,Change,1970,1971,1972,1973,1974,1975,1976,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,"Afghanistan, Islamic Rep. of",Degree Celsius,Surface Temperature Change,0.898,0.652,-1.089,0.262,-0.470,-0.468,-0.295,...,0.234,1.308,0.457,1.101,1.607,1.568,1.580,0.960,0.544,1.421
1,Albania,Degree Celsius,Surface Temperature Change,-0.119,-0.200,-0.077,-0.299,-0.134,-0.203,-0.672,...,1.568,1.444,1.322,1.665,1.601,1.269,2.146,1.823,1.623,1.682
2,Algeria,Degree Celsius,Surface Temperature Change,0.114,-0.380,-0.342,-0.028,-0.502,-0.554,-0.817,...,1.128,1.173,1.676,1.101,1.736,1.498,1.211,1.094,1.913,2.317
3,American Samoa,Degree Celsius,Surface Temperature Change,-0.036,-0.473,-0.070,0.322,-0.317,-0.128,-0.186,...,0.646,0.883,0.554,0.394,0.924,0.820,0.574,0.924,0.815,0.653
4,"Andorra, Principality of",Degree Celsius,Surface Temperature Change,0.081,-0.355,-0.526,-0.010,-0.412,0.207,-0.081,...,1.196,0.757,1.857,1.546,1.830,1.771,1.761,1.813,2.401,1.367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,Western Sahara,Degree Celsius,Surface Temperature Change,0.547,-0.620,-1.104,-0.013,-0.600,-0.267,-0.990,...,1.234,1.282,1.244,1.277,1.636,2.078,0.851,1.430,2.026,1.557
223,World,Degree Celsius,Surface Temperature Change,0.153,-0.089,-0.193,0.271,-0.179,0.091,-0.310,...,1.058,1.007,1.042,1.406,1.658,1.424,1.284,1.449,1.713,1.442
224,"Yemen, Rep. of",Degree Celsius,Surface Temperature Change,0.388,-0.199,0.049,0.333,-0.108,0.031,-0.074,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,Zambia,Degree Celsius,Surface Temperature Change,0.354,-0.249,-0.146,0.386,-0.393,-0.116,-0.297,...,0.926,0.746,0.638,1.486,1.474,0.721,0.727,1.295,1.252,1.002
226,Zimbabwe,Degree Celsius,Surface Temperature Change,0.427,-0.033,-0.367,0.627,-0.471,-0.253,-0.430,...,0.329,0.102,-0.008,0.808,1.051,0.116,0.405,0.939,0.415,-0.101

In [96]:
# Filling the BLank data using interpolation method 
year_columns = data.columns[3:]  
data[year_columns] = data[year_columns].apply(pd.to_numeric, errors='coerce')
data[year_columns] = data[year_columns].interpolate(method='linear', axis=1, limit_direction='both')

In [97]:
data

,Country Name,Unit,Change,1970,1971,1972,1973,1974,1975,1976,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,"Afghanistan, Islamic Rep. of",Degree Celsius,Surface Temperature Change,0.898,0.652,-1.089,0.262,-0.470,-0.468,-0.295,...,0.234,1.308,0.457,1.101,1.607,1.568,1.580,0.960,0.544,1.421
1,Albania,Degree Celsius,Surface Temperature Change,-0.119,-0.200,-0.077,-0.299,-0.134,-0.203,-0.672,...,1.568,1.444,1.322,1.665,1.601,1.269,2.146,1.823,1.623,1.682
2,Algeria,Degree Celsius,Surface Temperature Change,0.114,-0.380,-0.342,-0.028,-0.502,-0.554,-0.817,...,1.128,1.173,1.676,1.101,1.736,1.498,1.211,1.094,1.913,2.317
3,American Samoa,Degree Celsius,Surface Temperature Change,-0.036,-0.473,-0.070,0.322,-0.317,-0.128,-0.186,...,0.646,0.883,0.554,0.394,0.924,0.820,0.574,0.924,0.815,0.653
4,"Andorra, Principality of",Degree Celsius,Surface Temperature Change,0.081,-0.355,-0.526,-0.010,-0.412,0.207,-0.081,...,1.196,0.757,1.857,1.546,1.830,1.771,1.761,1.813,2.401,1.367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,Western Sahara,Degree Celsius,Surface Temperature Change,0.547,-0.620,-1.104,-0.013,-0.600,-0.267,-0.990,...,1.234,1.282,1.244,1.277,1.636,2.078,0.851,1.430,2.026,1.557
223,World,Degree Celsius,Surface Temperature Change,0.153,-0.089,-0.193,0.271,-0.179,0.091,-0.310,...,1.058,1.007,1.042,1.406,1.658,1.424,1.284,1.449,1.713,1.442
224,"Yemen, Rep. of",Degree Celsius,Surface Temperature Change,0.388,-0.199,0.049,0.333,-0.108,0.031,-0.074,...,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061,0.061
225,Zambia,Degree Celsius,Surface Temperature Change,0.354,-0.249,-0.146,0.386,-0.393,-0.116,-0.297,...,0.926,0.746,0.638,1.486,1.474,0.721,0.727,1.295,1.252,1.002
226,Zimbabwe,Degree Celsius,Surface Temperature Change,0.427,-0.033,-0.367,0.627,-0.471,-0.253,-0.430,...,0.329,0.102,-0.008,0.808,1.051,0.116,0.405,0.939,0.415,-0.101

In [98]:
data.isnull().sum()

Country Name    0
Unit            0
Change          0
1970            0
1971            0
1972            0
1973            0
1974            0
1975            0
1976            0
1977            0
1978            0
1979            0
1980            0
1981            0
1982            0
1983            0
1984            0
1985            0
1986            0
1987            0
1988            0
1989            0
1990            0
1991            0
1992            0
1993            0
1994            0
1995            0
1996            0
1997            0
1998            0
1999            0
2000            0
2001            0
2002            0
2003            0
2004            0
2005            0
2006            0
2007            0
2008            0
2009            0
2010            0
2011            0
2012            0
2013            0
2014            0
2015            0
2016            0
2017            0
2018            0
2019            0
2020            0
2021            0
dtype: int64

In [99]:
data.describe()

,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
count,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,...,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000,227.000000
mean,0.139916,-0.099326,-0.002145,0.260357,-0.075475,0.041932,-0.142165,0.208672,0.133407,0.273631,...,0.862383,0.892383,1.062648,1.211907,1.376170,1.223640,1.245326,1.375469,1.481088,1.273696
std,0.448322,0.416172,0.487646,0.421913,0.446775,0.500998,0.472734,0.373511,0.407615,0.467246,...,0.457709,0.362065,0.583651,0.501528,0.470346,0.445165,0.639085,0.528790,0.668073,0.554810
min,-1.294000,-1.294000,-1.796000,-1.294000,-1.294000,-1.294000,-1.294000,-1.294000,-1.294000,-1.302000,...,-0.313000,-0.313000,-0.313000,-0.313000,-0.313000,-0.313000,-0.313000,-0.313000,-0.313000,-0.313000
25%,-0.038500,-0.300000,-0.176000,0.047000,-0.328500,-0.258500,-0.407500,0.015000,-0.005000,0.103000,...,0.559500,0.664000,0.700000,0.951000,1.113500,0.965000,0.786000,1.057000,1.093500,0.950000
50%,0.145000,-0.164000,0.002000,0.262000,-0.159000,-0.100000,-0.205000,0.204000,0.132000,0.299000,...,0.787000,0.901000,0.932000,1.221000,1.395000,1.214000,1.108000,1.364000,1.404000,1.266000
75%,0.336500,-0.014500,0.192000,0.471500,0.060000,0.191000,0.024000,0.347000,0.247000,0.493000,...,1.139000,1.172500,1.340000,1.472000,1.701500,1.504500,1.674000,1.674000,1.828500,1.674000
max,1.636000,1.636000,1.636000,1.636000,1.636000,1.898000,1.636000,1.636000,1.636000,1.636000,...,2.165000,1.684000,2.711000,2.605000,2.454000,2.486000,2.781000,2.713000,3.693000,2.543000

In [100]:
# Saving the final data cleaning dataset for modeling
data.to_csv("../data/cleaned_data.csv", index=False)